// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// GIO FFI bindings
class GIO {
  /// Holds the Dynamic library.
  final ffi.DynamicLibrary _dylib;

  /// The symbols are looked up in [dynamicLibrary].
  GIO(ffi.DynamicLibrary dynamicLibrary) : _dylib = dynamicLibrary;

  ffi.Pointer<ffi.Int8> g_application_get_application_id(
    ffi.Pointer<GApplication> application,
  ) {
    _g_application_get_application_id ??= _dylib.lookupFunction<
            _c_g_application_get_application_id,
            _dart_g_application_get_application_id>(
        'g_application_get_application_id');
    return _g_application_get_application_id(
      application,
    );
  }

  _dart_g_application_get_application_id _g_application_get_application_id;

  ffi.Pointer<GApplication> g_application_get_default() {
    _g_application_get_default ??= _dylib.lookupFunction<
        _c_g_application_get_default,
        _dart_g_application_get_default>('g_application_get_default');
    return _g_application_get_default();
  }

  _dart_g_application_get_default _g_application_get_default;
}

class GTypeClass extends ffi.Struct {
  @ffi.Uint64()
  int g_type;
}

class GTypeInstance extends ffi.Struct {
  ffi.Pointer<GTypeClass> g_class;
}

class GData extends ffi.Struct {}

class GObject extends ffi.Struct {}

class GApplicationPrivate extends ffi.Struct {}

class GApplication extends ffi.Struct {}

typedef _c_g_application_get_application_id = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<GApplication> application,
);

typedef _dart_g_application_get_application_id = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<GApplication> application,
);

typedef _c_g_application_get_default = ffi.Pointer<GApplication> Function();

typedef _dart_g_application_get_default = ffi.Pointer<GApplication> Function();
